### ISSUE TITLE
Camera  and trackable issues To-Do

### ISSUE THREAD

**Issue by sycrus** [sycrus/major-studio-2#3]
- [ ] Using edges instead of polygons (ofBox2d.h)

- [ ] Kinect depth using ofKinect

- [ ] Shape contour detection using Kinect's IR channel

- [ ] Tracking with and without retroreflective stickers

- [ ] Projection testing on top of markers
